export const UI_CLIENT = String.raw`(function(){
"use strict";
var state={audits:[],selected:null,doctor:null,busy:false,review:null};var toastTimer;
function id(value){return document.getElementById(value)}
function el(tag,className,text){var value=document.createElement(tag);if(className)value.className=className;if(text!==undefined&&text!==null)value.textContent=String(text);return value}
function add(parent){for(var i=1;i<arguments.length;i+=1)if(arguments[i])parent.appendChild(arguments[i]);return parent}
function clear(value){while(value.firstChild)value.removeChild(value.firstChild)}
function short(value,size){if(!value)return "—";var text=String(value),length=size||12;return text.length>length+5?text.slice(0,length)+"…"+text.slice(-4):text}
function date(value){var parsed=new Date(value);return Number.isNaN(parsed.getTime())?String(value||"Unknown"):new Intl.DateTimeFormat(undefined,{month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"}).format(parsed)}
function badge(value,label){var normalized=String(value||"unknown").toLowerCase();return el("span","badge badge-"+normalized.replace(/[^a-z0-9-]/g,"-"),(label?label+" ":"")+normalized)}
function auditStatusBadges(audit){var box=el("div","status-pair");add(box,badge(audit.reviewStatus,"Review"),badge(audit.executionStatus,"Execution"));return box}
function action(label,className,handler){var value=el("button","button "+(className||"ghost"),label);value.type="button";if(handler)value.addEventListener("click",handler);return value}
function safeLink(value){try{var parsed=new URL(value);if(parsed.protocol!=="http:"&&parsed.protocol!=="https:")throw new Error();var link=el("a","",value);link.href=parsed.href;link.target="_blank";link.rel="noreferrer noopener";return link}catch(_error){return el("span","",value||"—")}}
function busy(active,message){state.busy=active;var status=id("operation-status");id("busy").classList.toggle("active",active);id("busy").setAttribute("aria-hidden",active?"false":"true");document.body.setAttribute("aria-busy",active?"true":"false");status.hidden=!active;status.textContent=active?(message||"Operation in progress. No result has been inferred."):"";document.querySelectorAll("button").forEach(function(button){button.disabled=active&&!button.hasAttribute("data-close")})}
function toast(message,error,duration){var value=id("toast");value.textContent=message;value.className="toast visible"+(error?" error":"");if(toastTimer)clearTimeout(toastTimer);toastTimer=setTimeout(function(){value.className="toast"},duration||4200)}
async function api(path,options){var request=Object.assign({method:"GET",headers:{accept:"application/json"},credentials:"omit"},options||{});if(request.body!==undefined&&typeof request.body!=="string"){request.headers["content-type"]="application/json";request.body=JSON.stringify(request.body)}var response=await fetch(path,request),body=null;try{body=await response.json()}catch(_error){}if(!response.ok){var message=body&&body.error&&body.error.message?body.error.message:"Request failed with HTTP "+response.status;throw new Error(message)}return body}
function system(failed){var box=id("system"),label=id("system-label");box.classList.remove("ready","blocked");if(failed||!state.doctor){box.classList.add("blocked");label.textContent="API unavailable"}else if(state.doctor.installed&&state.doctor.authenticated&&state.doctor.runnerReady){box.classList.add("ready");label.textContent="Kane "+(state.doctor.version||"ready")}else{box.classList.add("blocked");label.textContent="Kane setup required"}}
function metrics(){var claims=state.audits.reduce(function(all,audit){return all.concat(audit.claims||[])},[]),runs=state.audits.reduce(function(all,audit){return all.concat(audit.runs||[])},[]);id("m-audits").textContent=state.audits.length;id("m-verified").textContent=claims.filter(function(c){return c.verdict==="verified"&&c.freshness==="current"}).length;id("m-receipts").textContent=state.audits.reduce(function(sum,a){return sum+(a.receiptIds||[]).length},0);id("m-blocked").textContent=runs.filter(function(r){return r.verdict==="blocked"}).length;id("audit-count").textContent=state.audits.length}
async function load(preserve){if(state.busy)return;busy(true,"Refreshing local proof state…");try{var results=await Promise.all([api("/api/doctor"),api("/api/audits")]);state.doctor=results[0];state.audits=results[1].audits||[];system(false);metrics();renderList();if(preserve&&state.selected)await select(state.selected.id);else if(state.audits.length)await select(state.audits[0].id);else empty();toast("Workspace is current.")}catch(error){system(true);toast(error.message,true)}finally{busy(false)}}
function renderList(){var list=id("audit-list");clear(list);if(!state.audits.length){list.appendChild(el("p","citation","No local audits yet."));return}state.audits.forEach(function(audit){var card=el("button","audit-card"+(state.selected&&state.selected.id===audit.id?" active":""));card.type="button";var top=el("div");add(top,auditStatusBadges(audit),el("span","count",(audit.claims||[]).length+" claims"));add(card,top,el("h3","",audit.projectSlug),el("p","",audit.id));card.addEventListener("click",function(){select(audit.id)});list.appendChild(card)})}
function empty(){state.selected=null;var stage=id("stage"),box=el("div","empty");clear(stage);add(box,el("div","orbit"),el("p","index","No audit selected"),el("h3","","Choose an audit or begin with a README."),el("p","","The source stays exact. Every browser result stays attached to the bytes that produced it."),action("Create your first audit","dark",openCreate));stage.appendChild(box)}
async function select(auditId){try{var audit=await api("/api/audits/"+encodeURIComponent(auditId));state.selected=audit;update(audit);renderList();metrics();renderAudit()}catch(error){toast(error.message,true)}}
function update(audit){var index=state.audits.findIndex(function(item){return item.id===audit.id});if(index>=0)state.audits[index]=audit;else state.audits.unshift(audit)}
function binding(label,value,isUrl){var box=el("div","binding");add(box,el("span","",label),isUrl?safeLink(value):el("strong","",value||"—"));return box}
function titleRow(title,detail){var box=el("div","block-title");add(box,el("h3","",title),el("span","",detail));return box}
function renderAudit(){var audit=state.selected;if(!audit)return empty();var stage=id("stage"),detail=el("div","detail"),head=el("div","audit-head"),identity=el("div"),actions=el("div","audit-actions");clear(stage);add(identity,auditStatusBadges(audit),el("h2","",audit.projectSlug),el("p","",audit.id+" · revision "+audit.recordRevision));add(actions,action("Check freshness","ghost",freshness),action("Refresh","light",function(){select(audit.id)}));add(head,identity,actions);var bindings=el("div","bindings");add(bindings,binding("README source",audit.source.displayName+" · "+audit.source.locator),binding("Target",audit.target.url,true),binding("Deployment revision",audit.target.revision||"Not bound"),binding("Target binding",audit.target.fingerprintKind+(audit.target.fingerprintKind==="observed-manifest-v3"?" · current policy":" · legacy/not current-policy")),binding("Manifest hash",audit.target.observation&&audit.target.observation.manifestHash?audit.target.observation.manifestHash:"Legacy unavailable"),binding("Entrypoint",audit.target.observation&&audit.target.observation.entrypointUrl?audit.target.observation.entrypointUrl:"Legacy unavailable",Boolean(audit.target.observation&&audit.target.observation.entrypointUrl)),binding("Entrypoint hash",audit.target.observation&&audit.target.observation.entrypointHash?audit.target.observation.entrypointHash:"Legacy unavailable"));var claims=el("div","claims");(audit.claims||[]).forEach(function(claim){claims.appendChild(renderClaim(audit,claim))});add(detail,head,bindings,titleRow("Claims",audit.claims.length+" extracted"),claims);if(audit.runs.length){var runs=el("div");audit.runs.slice().reverse().forEach(function(run){runs.appendChild(renderRun(run))});add(detail,titleRow("Execution history",audit.runs.length+" immutable attempts"),runs)}if(audit.receiptIds.length){var receipts=el("div","receipts");audit.receiptIds.slice().reverse().forEach(function(receiptId){var item=el("button","receipt-link",short(receiptId,20));item.type="button";item.title=receiptId;item.addEventListener("click",function(){openReceipt(receiptId)});receipts.appendChild(item)});add(detail,titleRow("Receipts",audit.receiptIds.length+" source-bound records"),receipts)}stage.appendChild(detail)}
function proof(label,value){var box=el("div","proof");add(box,el("span","",label),el("code","",value||"—"));return box}
function check(labelText,checked){var label=el("label","check"),input=el("input");input.type="checkbox";input.checked=Boolean(checked);add(label,input,el("span","",labelText));return{label:label,input:input}}
function renderClaim(audit,claim){var card=el("article","claim"),top=el("div","claim-top");add(top,badge(claim.reviewStatus),badge(claim.verdict),badge(claim.freshness));add(card,top,el("blockquote","",claim.quote),el("div","citation",claim.citation.locator+" · lines "+claim.citation.lineStart+"–"+claim.citation.lineEnd));var details=el("details"),summary=el("summary","","Inspect deterministic bindings"),grid=el("div","proof-grid");add(grid,proof("Assertion kind",claim.assertion?claim.assertion.kind:"unverifiable"),proof("Assertion hash",claim.assertionHash),proof("Plan hash",claim.assertionPlanHash),proof("Test hash",claim.testHash));add(details,summary,grid);card.appendChild(details);var actions=el("div","claim-actions");if(claim.reviewStatus!=="approved"&&claim.testability==="testable")actions.appendChild(action("Approve claim","dark",function(){decide(audit.id,claim.id,"approve")}));if(claim.reviewStatus!=="approved")actions.appendChild(action("Cannot verify","ghost",function(){openReview(audit.id,claim,"unverifiable")}));if(claim.reviewStatus==="proposed")actions.appendChild(action("Reject","ghost danger",function(){openReview(audit.id,claim,"reject")}));if(claim.reviewStatus==="approved"&&claim.testability==="testable"&&audit.target.fingerprintKind==="observed-manifest-v3"){var headless=check("Headless",true),run=action("Run Kane","dark"),checks=el("div","checks");add(checks,headless.label,run);actions.appendChild(checks);var advanced=el("details","advanced"),row=el("div"),author=check("Author fresh test"),retry=check("Retry execution"),push=check("Push to Kane account");add(advanced,el("summary","","Advanced Kane execution"));add(row,author.label,retry.label,push.label);advanced.appendChild(row);actions.appendChild(advanced);run.addEventListener("click",function(){verify(audit.id,claim.id,{headless:headless.input.checked,author:author.input.checked,retry:retry.input.checked,push:push.input.checked,timeoutSeconds:120})})}if(!actions.childNodes.length)actions.appendChild(el("span","citation",claim.testability==="unverifiable"?"Outside the supported browser assertion grammar.":audit.target.fingerprintKind!=="observed-manifest-v3"?"Legacy target binding is read-only; re-ingest to run under current manifest policy.":"Decision recorded."));card.appendChild(actions);return card}
function hashBox(label,value){var box=el("div","hash");add(box,el("span","",label),el("code","",value||"unavailable"));box.title=value||"unavailable";return box}
function renderRun(run){var box=el("article","run"),main=el("div"),heading=el("h4"),tuple=el("div","tuple"),hashes=el("div","hashes"),hashStatus=run.testBytesUnchanged===true?"MATCH":run.testBytesUnchanged===false?"MISMATCH":"LEGACY UNAVAILABLE";add(heading,badge(run.verdict),document.createTextNode("  "+short(run.id,18)));add(main,heading,el("p","",run.summary||"No terminal summary."));add(hashes,hashBox("Pre-execution",run.testHashBefore),el("span","hash-arrow",hashStatus),hashBox("Post-execution",run.testHashAfter));main.appendChild(hashes);add(tuple,el("span","","exit "+(run.exitCode===null?"—":run.exitCode)),el("span","",run.terminalStatus||"no terminal"),el("span","","claim "+(run.claimSatisfied===null||run.claimSatisfied===undefined?"—":run.claimSatisfied)),el("span","","protocol "+(run.protocol?run.protocol.mode:"legacy unavailable")));add(box,el("time","",date(run.completedAt)),main,tuple);return box}
function openCreate(){id("create-dialog").showModal()}
function openReview(auditId,claim,decision){state.review={auditId:auditId,claimId:claim.id};id("review-quote").textContent=claim.quote;id("review-decision").value=decision;var textarea=id("review-form").elements.reason;textarea.value=decision==="unverifiable"?"This statement cannot be compiled into an objective supported browser assertion.":"This claim should not enter the verification queue.";id("review-dialog").showModal()}
async function create(form){var data=new FormData(form),payload={project:String(data.get("project")||"").trim(),readme:String(data.get("readme")||"").trim(),targetUrl:String(data.get("targetUrl")||"").trim(),targetRevision:String(data.get("targetRevision")||"").trim()||null};busy(true,"Observing the target and extracting exact claims…");try{var audit=await api("/api/audits",{method:"POST",body:payload});id("create-dialog").close();state.selected=audit;update(audit);renderList();metrics();renderAudit();toast("Audit created. Review each browser-verifiable claim.")}catch(error){toast(error.message,true,7000)}finally{busy(false)}}
async function decide(auditId,claimId,decision,reason){busy(true,"Recording claim decision…");try{var payload={decision:decision};if(reason)payload.reason=reason;var audit=await api("/api/audits/"+encodeURIComponent(auditId)+"/claims/"+encodeURIComponent(claimId),{method:"PATCH",body:payload});id("review-dialog").close();state.selected=audit;update(audit);renderList();metrics();renderAudit();toast(decision==="approve"?"Claim approved without changing its assertion.":"Decision recorded.")}catch(error){toast(error.message,true,7000)}finally{busy(false)}}
async function verify(auditId,claimId,options){if((options.author||options.push)&&!confirm("This requests a distinct Kane execution"+(options.push?" and publishes it to the authenticated Kane account":"")+". Continue?"))return;busy(true,"Kane is running immutable browser-test bytes. No verdict is inferred while it is in flight.");try{var result=await api("/api/audits/"+encodeURIComponent(auditId)+"/verify",{method:"POST",body:Object.assign({claimId:claimId},options)});state.selected=result.audit;update(result.audit);renderList();metrics();renderAudit();var unchanged=result.run.testBytesUnchanged===true;toast("Kane result: "+result.run.verdict+". Test bytes "+(unchanged?"unchanged.":"did not remain identically observed."),!unchanged||result.run.verdict==="blocked",9000);if(result.receipt)await openReceipt(result.receipt.id)}catch(error){toast(error.message,true,9000)}finally{busy(false)}}
async function freshness(){if(!state.selected)return;busy(true,"Rechecking source, target, assertion, and test bindings…");try{var audit=await api("/api/audits/"+encodeURIComponent(state.selected.id)+"/freshness",{method:"POST",body:{}});state.selected=audit;update(audit);renderList();metrics();renderAudit();toast("Freshness evaluated independently from verdict.")}catch(error){toast(error.message,true,7000)}finally{busy(false)}}
function receiptBinding(label,value){var box=el("div","receipt-binding");add(box,el("span","",label),el("code","",value||"—"));return box}
async function openReceipt(receiptId,provided){try{var receipt=provided||await api("/api/receipts/"+encodeURIComponent(receiptId)),content=id("receipt-content"),hero=el("div","receipt-hero"),identity=el("div"),tuple=el("div","receipt-tuple"),bindings=el("div","receipt-bindings"),policy=receipt.policyAssessment||{validity:"legacy",basis:"receipt-version",declaredPolicyVersion:null},successors=(receipt.supersededByReceiptIds||[]).join(", ")||"None";clear(content);add(identity,badge(receipt.verdict),el("h3","",receipt.verdict==="verified"?"Claim verified.":"Claim disproved."),el("p","","Evidence policy: "+String(policy.validity).toUpperCase()+" ("+policy.basis+")"),el("p","","Lineage: "+String(receipt.lineageStatus||"current").toUpperCase()));add(hero,identity,el("p","",receipt.id));[["Process exit",receipt.exitCode],["Terminal",receipt.terminalStatus],["Claim satisfied",receipt.claimSatisfied],["Protocol mode",receipt.protocol?receipt.protocol.mode:"legacy unavailable"]].forEach(function(item){var cell=el("div");add(cell,el("span","",item[0]),el("strong","",item[1]===null||item[1]===undefined?"—":item[1]));tuple.appendChild(cell)});add(bindings,receiptBinding("Receipt format","v"+receipt.version),receiptBinding("Declared policy",policy.declaredPolicyVersion===null?"Legacy unavailable":"v"+policy.declaredPolicyVersion),receiptBinding("Source hash",receipt.sourceHash),receiptBinding("Target fingerprint",receipt.targetFingerprint),receiptBinding("Target binding",receipt.targetBindingKind||"Legacy revision marker"),receiptBinding("Manifest hash",receipt.targetManifestHash||"Legacy unavailable"),receiptBinding("Entrypoint URL",receipt.targetEntrypointUrl||"Legacy unavailable"),receiptBinding("Entrypoint hash",receipt.targetEntrypointHash||"Legacy unavailable"),receiptBinding("Test hash",receipt.testHash),receiptBinding("Pre-execution hash",receipt.testHashBefore||"LEGACY UNAVAILABLE"),receiptBinding("Post-execution hash",receipt.testHashAfter||"LEGACY UNAVAILABLE"),receiptBinding("Assertion plan",receipt.assertionPlanHash),receiptBinding("Kane run",receipt.kaneRunId),receiptBinding("Predecessor",receipt.supersedesReceiptId||"First receipt"),receiptBinding("Successors",successors));add(content,hero,el("blockquote","receipt-quote",receipt.claimQuote),tuple,bindings);id("receipt-dialog").showModal()}catch(error){toast(error.message,true)}}
function bind(){document.querySelectorAll("[data-create]").forEach(function(value){value.addEventListener("click",openCreate)});document.querySelectorAll("[data-refresh]").forEach(function(value){value.addEventListener("click",function(){load(true)})});document.querySelectorAll("[data-close]").forEach(function(value){value.addEventListener("click",function(){value.closest("dialog").close()})});document.querySelectorAll("dialog").forEach(function(dialog){dialog.addEventListener("click",function(event){if(event.target===dialog)dialog.close()})});id("create-form").addEventListener("submit",function(event){event.preventDefault();create(event.currentTarget)});id("review-form").addEventListener("submit",function(event){event.preventDefault();if(!state.review)return;var data=new FormData(event.currentTarget);decide(state.review.auditId,state.review.claimId,String(data.get("decision")),String(data.get("reason")||"").trim())})}
bind();load(false);
})();
`;